### ISSUE TITLE
Docs not working

### ISSUE THREAD

**Issue by jd-solanki** [antfu/utils#37] opened 2023-09-23 19:08 UTC
### Describe the bug

![image](https://github.com/antfu/utils/assets/47495003/56868272-2dea-449d-b199-fff5046477fb)

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by s3xysteak** [comment] 2024-03-12 11:40
Document plz 😢

**Comment by antfu** [comment] 2024-03-13 06:40
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-13 06:40 UTC

**Comment by jd-solanki** [comment] 2024-03-13 16:53
Hi @antfu 

Thanks for commenting. I totally forgot about the issue even after another comment. I should update the issue to make it more clear.

The issue is docs site which is located at https://www.paka.dev/npm/@antfu/utils is resulting in error and we are unable to view the docs for your utils. Try visiting the above link.

P.S. I'm updating the issue...

**Comment by antfu** [comment] 2024-03-13 17:56
I guess paka.dev probably no longer maintained, we could switch to https://www.jsdocs.io/package/@antfu/utils
